@HostAddress = http://localhost:5268
@json = application/json
@jwtToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmNzk3NDYxNy1mYmUzLTQwY2YtYTIwOS04MjM1YmMwZGIyOTUiLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwianRpIjoiMWFmMTkzNmQtMWFjYS00ZDdiLTg4Y2EtNWRkNWZjZDVkZDNjIiwibmFtZSI6IkFkbWluIEFkbWluaXN0cmF0b3IiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTc4OTY2MzYxNSwiaXNzIjoiSG90ZWxMaXN0aW5nQVBJIiwiYXVkIjoiSG90ZWxMaXN0aW5nQVBJQ2xpZW50In0.THPyWzadb683ixMkgcC6iG7jy1OX8zDPvIxEpNQu6RA

###############################################
# COUNTRIES ENDPOINTS
###############################################

### 1. Get All Countries (Unpaginated list)
GET {{HostAddress}}/api/countries
Accept: {{json}}
Authorization: {{jwtToken}}

###

### 2. Get Filtered & Sorted Countries (Search=is, SortBy=name)
GET {{HostAddress}}/api/countries?Search=is&SortBy=name&SortDescending=false
Accept: {{json}}
Authorization: {{jwtToken}}

###

@countryId = 2
@pageNumber = 1
@pageSize = 10
### 3. Get Hotels for a Country (Custom Pagination & Filters: MinRating=4.5, SortBy=rating)
GET {{HostAddress}}/api/countries/{{countryId}}/hotels?pageNumber={{pageNumber}}&pageSize={{pageSize}}&MinRating=4.5&SortBy=rating&SortDescending=true
Accept: {{json}}
Authorization: {{jwtToken}}

###

### 4. Get Country By ID
GET {{HostAddress}}/api/countries/2
Accept: {{json}}
Authorization: {{jwtToken}}

###

### 5. Create New Country (Admin Only)
POST {{HostAddress}}/api/countries
Content-Type: {{json}}
Authorization: {{jwtToken}}

{
  "name": "United Kingdom",
  "shortName": "UK"
}

###

### 6. Update Country (Admin Only)
PUT {{HostAddress}}/api/countries/1
Content-Type: {{json}}
Authorization: {{jwtToken}}

{
  "id": 1,
  "name": "Ukraine",
  "shortName": "UA"
}

###

### 7. Partially Update Country (PATCH - Admin Only)
PATCH {{HostAddress}}/api/countries/1
Content-Type: application/json-patch+json
Authorization: {{jwtToken}}

[
  {
    "op": "replace",
    "path": "/shortName",
    "value": "UA"
  }
]

###

### 8. Delete Country By ID (Admin Only)
DELETE {{HostAddress}}/api/countries/1002
Authorization: {{jwtToken}}

###
