@HostAddress = http://localhost:5268
@json = application/json
@jwtToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmNzk3NDYxNy1mYmUzLTQwY2YtYTIwOS04MjM1YmMwZGIyOTUiLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwianRpIjoiZmNkMTc4ODAtYzZhMi00MzkwLTg5NTctMjYyZmVlMTMxOWVhIiwibmFtZSI6IkFkbWluIEFkbWluaXN0cmF0b3IiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTc4OTA0ODcyMywiaXNzIjoiSG90ZWxMaXN0aW5nQVBJIiwiYXVkIjoiSG90ZWxMaXN0aW5nQVBJQ2xpZW50In0.3J5mjBgAt8Kuc4dyQ5uCUsmqsJIQEeq1hJnOptwSlBM

###############################################
# COUNTRIES ENDPOINTS
###############################################

### 1. Get All Countries
GET {{HostAddress}}/api/countries
Accept: {{json}}
Authorization: {{jwtToken}}

###

### 2. Get Country By ID
GET {{HostAddress}}/api/countries/1
Accept: {{json}}
Authorization: {{jwtToken}}

###

### 3. Create New Country
POST {{HostAddress}}/api/countries
Content-Type: {{json}}
Authorization: {{jwtToken}}

{
  "name": "United Kingdom",
  "shortName": "UK"
}

###

### 4. Update Country
PUT {{HostAddress}}/api/countries/1
Content-Type: {{json}}

{
  "id": 1,
  "name": "Jamaica",
  "shortName": "JM"
}

###

### 5. Delete Country By ID
DELETE {{HostAddress}}/api/countries/1

###

